# Linear Regression

After exploring the Exoplanet dataset, I noticed that a considerable number of planets were lacking data points for their effective temperature and inclination, with 1396 and 1286 planets missing each, respectively.

While linear regression method can be used for filling in missing data, it should be done with caution when a multitude of other variables also have missing values. This is because correlations between variables can become unstable and result in further complications.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import copy
import math

df = pd.read_csv('exoplanet_dataset.csv')

# Drop the uncertainties and limit columns to simplify the data
df = df.drop([col_name for col_name in df if col_name.endswith(('err1', 'err2', 'lim'))], axis=1)

# Update the data type int64 into bool on boolean columns as documented in the column definition
bool_col_names = ['rv_flag', 'pul_flag', 'ptv_flag', 'tran_flag', 'ast_flag', 'obm_flag', 'micro_flag', 'etv_flag', 'ima_flag', 'dkin_flag', 'ttv_flag', 'cb_flag']
df[bool_col_names] = df[bool_col_names].astype(bool)

col_to_remove = list((df.isnull().sum() / len(df)).loc[lambda p : p > 0.3].sort_values(ascending=False).index) # Drop columns with missing data >= 30%
df = df.drop(col_to_remove, axis=1)
df = df.drop(['pl_rade', 'pl_bmasse'], axis=1) # Drop highly correlated value
df = df.drop(['discoverymethod'], axis=1) # Use one-hot encoded columns
df = df.drop(['pl_name', 'hostname', 'disc_year', 'disc_locale', 'disc_facility', 'disc_telescope', 'disc_instrument', 'pl_bmassprov', 'st_metratio', 'ra_reflink'], axis=1) # Drop non numeric fields
df = df.dropna() # Drop nan values

## Standardization

Standardization rescales the data so that the dataset has a mean of $\mu = 0$ and standard deviation of $\sigma = 1$.

$${x_{new}}^{(i)} = {{(x^{(i)} - \mu)} \over \sigma}$$

## Normalization

Normalization rescales the data so that each of the value falls between 0 and 1.

$${x_{new}}^{(i)} = {{(x^{(i)} - x_{min})} \over {(x_{max} - x_{min})}}$$ 


<br>


Since most of the planetary features have different ranges, they should be transformed to a common scale. For example, `pl_eqt` is measured in Kelvins ranging from 30 ~ 4100 in value whereas `pl_bmassj` is measured in Jupiter mass ranging from as small as 6e-05 to 700s. Since the temperature variable has a bigger range, it will outweigh the mass variable due to its larger value but it shouldn't imply that temperature value is more important predictor for the model. 

In [2]:
df = df[['pl_bmassj', 'pl_orbsmax', 'pl_eqt', 'st_mass', 'st_lum', 'st_logg']]

## Split dataset into Train and Test

Among the planets that have the temperature data, split the dataset into two groups: train(70%) and test(30%).

In [3]:
from sklearn.model_selection import train_test_split

temp_df = df[df['pl_eqt'].notnull()]
temp_pred_df = df[df['pl_eqt'].isnull()]
y = temp_df['pl_eqt']
X = temp_df.drop('pl_eqt', axis=1)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42) # random state is used to get the same output each time

X_train = np.array(X_train)
X_test = np.array(X_test)
y_train = np.array(y_train)
y_test = np.array(y_test)

print('X_train shape:', X_train.shape)
print('y_train shape:', y_train.shape)
print('X_test shape:', X_test.shape)
print('y_test shape:', y_test.shape)

X_train shape: (1993, 5)
y_train shape: (1993,)
X_test shape: (855, 5)
y_test shape: (855,)


## Compute cost

The model function for linear regression which is a function that maps from `X` (planet parameters) to `y` (planet effective temperature (K)) is represented as: $$f_{W,b}(X) = WX + b$$
To train this linear regression model, you need to find the best $(W,b)$ parameters that fit your dataset.
To compare how a one parameter $(W,b)$ is better or worse than another is by evaluating it with a cost function $J(W,b)$.


The cost function is defined as: $$J(W,b) = \frac{1}{2m} \sum\limits_{i = 0}^{m-1} (f_{W,b}(X^{(i)}) - y^{(i)})^2$$

where $m$ is the number of training examples, $f_{W,b}(X^{(i)})$ is the model's prediction of the planet's effective temperature and $y^{(i)}$ is the actual effective temperature from the dataset.

In [4]:
def compute_cost(X, y, W, b): 
    """
    Computes the cost function for multi-variable linear regression.
    
    Arguments:
    X: input matrix of shape (m, n) (Planet parameters) 
    y: output vector of shape (m, 1) (Actual effective temperature of the planet)
    W: weight vector of shape (1, n)
    b: bias scalar
    
    Returns
    cost -- scalar value of the cost function
    """
    
    m = X.shape[0] # number of training examples
    f_Wb = np.dot(X, W.T) + b  # predicted output values
    loss = (f_Wb - y)**2  # squared error 
    cost = np.sum(loss) / (2 * m)  # compute cost using mean squared error

    return cost

## Gradient descent

The parameter that fits the data best will have the smallest cost $J(W,b)$. Gradient descent is used to find that smallest cost by stepping closer to the optimal value. 
The algorithm for gradient descent is:
$$\begin{align*}& \text{repeat until convergence:} \; \lbrace \newline\; 
& \phantom {0000} b := b -  \alpha \frac{\partial J(W,b)}{\partial b} \newline\; 
& \phantom {0000} W := W -  \alpha \frac{\partial J(W,b)}{\partial W} \; \newline 
& \rbrace\end{align*}$$

where parameters $W$, $b$ are both updated simultaniously and where:
$$\frac{\partial J(W,b)}{\partial b}  = \frac{1}{m} \sum\limits_{i = 0}^{m-1} (f_{W,b}(X^{(i)}) - y^{(i)})$$

$$\frac{\partial J(W,b)}{\partial W}  = \frac{1}{m} \sum\limits_{i = 0}^{m-1} (f_{W,b}(X^{(i)}) -y^{(i)})X^{(i)}$$

In [5]:
def compute_gradient(X, y, W, b): 
    """
    Compute the gradient of the cost function for multi-variable linear regression.

    Arguments:
    X: input matrix of shape (m, n) (Planet parameters) 
    y: output vector of shape (m, 1) (Actual effective temperature of the planet)
    W: weight vector of shape (1, n)
    b: bias scalar
    
    Returns
    dj_dW: The gradient of the cost with respect to the parameters W
    dj_db: The gradient of the cost with respect to the parameter b     
    """
    
    m = X.shape[0]  # number of training examples
    f_Wb = np.dot(X, W.T) + b  # predicted output values
    diff = f_Wb - y  # difference between predicted and true output values

    dj_dW = np.dot(diff.T, X) / m  # gradient with respect to the weights
    dj_db = np.sum(diff) / m  # gradient with respect to the bias

    return dj_dW, dj_db

## Batch gradient descent

In [6]:
def gradient_descent(X, y, W_in, b_in, cost_function, gradient_function, alpha, num_iters): 
    """
    Performs batch gradient descent

    Arguments:
    X: input matrix of shape (m, n)
    y: output vector of shape (m, 1)
    W_in: initial weight vector of shape (1, n)
    b_in: initial bias scalar
    cost_function: function to compute the cost given X, y, W, and b
    gradient_function: function to compute the gradient of the cost function given X, y, W, and b
    alpha: learning rate
    num_iters: number of iterations to run gradient descent

    Returns:
    W: optimal weight vector of shape (1, n)
    b: optimal bias scalar
    """

    # An array to store cost J and w's at each iteration — primarily for graphing later
    J_history = []
    W_history = []
    W = copy.deepcopy(W_in)  # Avoid modifying global w within function
    b = b_in
    
    for i in range(num_iters):

        # Calculate the gradient and update the parameters
        dj_dW, dj_db = gradient_function(X, y, W, b)  

        # Update Parameters using w, b, alpha and gradient
        W = W - alpha * dj_dW               
        b = b - alpha * dj_db               

        # Save cost J at each iteration
        if i<100000:      # prevent resource exhaustion 
            cost = cost_function(X, y, W, b)
            J_history.append(cost)

        # Print cost every at intervals 10 times or as many iterations if < 10
        if i% math.ceil(num_iters/10) == 0:
            W_history.append(W)
            print(f"Iteration {i:4}: Cost {float(J_history[-1]):8.2f}   ")
        
    return W, b, J_history, W_history # Return W and J,W history for graphing

In [9]:
m,n = X.shape # m is the number of samples and n is the number of features

# Xavier Initialization
lower, upper = -(1.0 / math.sqrt(n)), (1.0 / math.sqrt(n))
numbers = np.random.rand(1000)
scaled = lower + numbers * (upper - lower)
initial_W = np.random.uniform(lower, upper, size=(1,n))
initial_b = 0

# gradient descent settings
iterations = 1500
alpha = 0.00001

-0.4472135954999579 0.4472135954999579
-0.4434834268503958 0.44633775991168917
-0.0062474354345094275 0.2560451467545742


In [10]:
W,b,J_history,W_history = gradient_descent(X_train, y_train, initial_W, initial_b, compute_cost, compute_gradient, alpha, iterations)
print("W,b found by gradient descent:", W, b)

Iteration    0: Cost 1014361752.30   
Iteration  150: Cost 188557078.77   
Iteration  300: Cost 175445955.71   
Iteration  450: Cost 164845270.00   
Iteration  600: Cost 154899956.85   
Iteration  750: Cost 145565039.46   
Iteration  900: Cost 136802229.66   
Iteration 1050: Cost 128575718.70   
Iteration 1200: Cost 120852002.90   
Iteration 1350: Cost 113599729.95   
W,b found by gradient descent: [[ -1.1168913   -0.68849723  -2.33995544   0.11104437 -11.98049429]
 [ -1.24060069  -0.7282982   -2.6310364    0.12711716 -13.29150032]
 [ -3.46736983  -1.44471569  -7.87049366   0.41642736 -36.88960877]
 ...
 [ -0.61667504  -0.52756287  -1.16297591   0.0460544   -6.67946993]
 [  0.73337097  -0.09321314   2.01360325  -0.12934864   7.62759582]
 [ -2.66056942  -1.18514413  -5.97213958   0.31160482 -28.33956947]] 913.7926365034399


In [13]:
def predict(X, W, b):
    """
    Predicts the target variable given the input features and learned parameters.

    Parameters:
    X: input matrix of shape (m, n)
    W: weight vector of shape (n, 1)
    b: bias scalar

    Returns:
    y_pred: predicted targe variable of shape shape (m, 1).
    """
    y_pred = np.dot(X, W.T) + b

    return y_pred

In [14]:
#Compute accuracy on our training set
p = predict(X_train, W,b)
print('Train Accuracy: %f'%(np.mean(p == y_train) * 100))

Train Accuracy: 0.000000
